### PR TITLE
Added Healer.php

### PR DESCRIPTION
**Pull request by noook**
Call the healer in poo.php with `$healerCharacter->healAlly($characterToHeal);`

### CODE REVIEW

**Comment by fenegan** [comment]
Due to the way it works your Healer should extend Mage instead of Character

**Comment by noook** [comment]
I extended the Mage class, and added additional logs for further clarity on the healed ally's health

**Comment by fenegan** [comment]
You should rename $c to $ally in healAlly()

**Comment by noook** [comment]
Done.

**Pull request merged**
